#!/bin/sh
# Change default theme to `argon`
for i in 1 2 3 4 5 6 7 8 9 10; do
    if grep "option Argon" /etc/config/luci >/dev/null 2>&1; then
        uci set luci.main.mediaurlbase='/luci-static/argon' &&
            uci commit
    fi
    sleep 1
done
