#!/bin/sh

# Btrfs 子卷自动挂载工具
# 请进行修改，然后移除 `exit 0`
exit 0

# 锁定文件，避免同时操作造成重复挂载
lock /tmp/btrfs-mounting-1

# 先去挂载点设置中设置一个 "根子卷"，可以是 subvol=/ 或 subvol=@ ，用于判断是否准备好挂载

# 检查当前事件是否为挂载 (mount)
if [ "$ACTION" = "add" ] || [ "$ACTION" = "change" ]; then
    sleep 2
    detected_uuid="$(blkid -s UUID -o value /dev/${DEVICENAME} | head -n 1)"
    case "${detected_uuid}" in
        6a5d7c5c-c9d0-41cc-8f19-78d97f839c05)
            # 这里的 UUID 替换为你硬盘分区的真实 UUID
            TARGET_UUID="${detected_uuid}"
            # 主挂载点（父卷）
            PARENT_MOUNT="/mnt/disk1"
            FIRST_MOUNT="/share/subvol_data"
            if mountpoint "$FIRST_MOUNT"; then
                echo "This btrfs disk is already mounted"
                exit 0
            fi

            # 检查主挂载点是否已经在线
            for i in $(seq 1 10); do
                if mountpoint -q "$PARENT_MOUNT"; then
                    logger -t BTRFS_MOUNT "Detected $PARENT_MOUNT is up, mounting subvolumes of disk ${TARGET_UUID}..."

                    # 挂载子卷 1
                    subvol_path="$FIRST_MOUNT"
                    if [ ! -d "$subvol_path" ]; then mkdir -p "$subvol_path"; fi
                    mount UUID="$TARGET_UUID" -t btrfs -o subvol=@data,compress=zstd "$subvol_path"

                    # 挂载子卷 2
                    subvol_path=/share/subvol_data2
                    if [ ! -d "$subvol_path" ]; then mkdir -p "$subvol_path"; fi
                    mount UUID="$TARGET_UUID" -t btrfs -o subvol=@data,compress=zstd "$subvol_path"

                    logger -t BTRFS_MOUNT "All subvolumes mounted successfully."
                    break
                else
                    echo "$PARENT_MOUNT is not mounted, waiting"
                fi
                sleep 2
            done
            ;;
        02880b1f-0c67-46b6-9b05-5535680ccc89)
            echo "another config"
            ;;
    esac
fi

lock -u /tmp/btrfs-mounting-1
